[package]
name = "mockito-foo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockito = { version = "1.0.2", path = "/home/tomi/src/mockito" }
